### ISSUE TITLE
Cant get Elden Ring to launch with modengine

### ISSUE THREAD

**Issue by cjghost2000** [soulsmods/ModEngine2#94]
It was working 2 days ago, but now it just refuses to launch with modengine I've looked through a bunch of issues and tried multiple things and nothing has worked i also checked logs and didn't see any errors, the game launches fine on its own but just refuses to launch with the launchers it just flashes the startup screen for a second then closes

things I've tried:
- removing my mods
- reinstalling the game
- moving my game to a different drive / the same one as steam
- older versions of modengine
- launchmod_eldenring.bat and modengine files as admin
- renaming the modengine launcher to start_protected_game
- made sure all the folders have the correct permissions

I also checked steam updates and the last one was on the 7th, so I don't know if that's the problem? I don't think it is because it was working on the 8th for me or maybe there was a hotfix ?
[modengine_2022-12-10.log](https://github.com/soulsmods/ModEngine2/files/10201165/modengine_2022-12-10.log)

**Comment by JaedenCross** [comment]
Alr, ma boy, in order for ModEngine to launch Elden Ring the game has to be in a **very specific** location... 

Your log says your resolved mod path is **(H:\SteamLibrary\steamapps\common\ELDEN RING\Game\mod)**

But ModEngine's code is very simple and It only searches one path for base Elden Ring. Yours is stored in ur steam library instead of "Program Files" like mine below.

**C:\Program Files\Steam\steamapps\common\ELDEN RING**

Idk if you're using an SSD or smthn, but I think u should try to put ur Elden Ring in the same path as mine.

**Comment by cjghost2000** [comment]
**after trying a ton of random fixes the cause of the problem was somehow epic games idk how or why but after uninstalling epic games i can now launch modded elden ring**
